# Generated by Django 5.1 on 2025-08-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformsubmission',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='contactformsubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
