# Generated by Django 5.1 on 2025-08-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_remove_contactformsubmission_contact_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformsubmission',
            name='id',
        ),
        migrations.AddField(
            model_name='contactformsubmission',
            name='contact_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
